"""create popular routes

Revision ID: 1008fc1bb7f5
Revises: 13dc09a3c276
Create Date: 2026-07-27 14:37:47.626974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1008fc1bb7f5'
down_revision: Union[str, Sequence[str], None] = '13dc09a3c276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('from_city', sa.String(length=100), nullable=False),
    sa.Column('to_city', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('distance', sa.String(length=50), nullable=False),
    sa.Column('trip_time', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_popular_routes_id'), 'popular_routes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_popular_routes_id'), table_name='popular_routes')
    op.drop_table('popular_routes')
    # ### end Alembic commands ###
