"""update locations table

Revision ID: 14b497fb0ef6
Revises: 22d30596da4e
Create Date: 2026-08-02 17:30:30.053036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b497fb0ef6'
down_revision: Union[str, Sequence[str], None] = '22d30596da4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('block', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('panchayat', sa.String(length=150), nullable=True))
    op.add_column('locations', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('locations', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('is_serviceable', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('locations', sa.Column('priority', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('locations', sa.Column('airport_code', sa.String(length=10), nullable=True))
    op.add_column('locations', sa.Column('railway_station_code', sa.String(length=10), nullable=True))
    op.add_column('locations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_location_block', 'locations', ['block'], unique=False)
    op.create_index('idx_location_pincode', 'locations', ['pincode'], unique=False)
    op.create_index('idx_location_serviceable', 'locations', ['is_serviceable'], unique=False)
    op.create_unique_constraint(None, 'locations', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='unique')
    op.drop_index('idx_location_serviceable', table_name='locations')
    op.drop_index('idx_location_pincode', table_name='locations')
    op.drop_index('idx_location_block', table_name='locations')
    op.drop_column('locations', 'created_at')
    op.drop_column('locations', 'railway_station_code')
    op.drop_column('locations', 'airport_code')
    op.drop_column('locations', 'priority')
    op.drop_column('locations', 'is_serviceable')
    op.drop_column('locations', 'slug')
    op.drop_column('locations', 'pincode')
    op.drop_column('locations', 'panchayat')
    op.drop_column('locations', 'block')
    op.drop_column('locations', 'country')
    # ### end Alembic commands ###
