"""create area banners

Revision ID: 1cb6c14abfc0
Revises: f34eb7b233b1
Create Date: 2026-08-16 10:42:28.241308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb6c14abfc0'
down_revision: Union[str, Sequence[str], None] = 'f34eb7b233b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('district_slug', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('banner_image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_area_banner_level_slug', 'area_banners', ['level', 'slug', 'district_slug'], unique=False)
    op.create_index(op.f('ix_area_banners_id'), 'area_banners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_area_banners_id'), table_name='area_banners')
    op.drop_index('idx_area_banner_level_slug', table_name='area_banners')
    op.drop_table('area_banners')
    # ### end Alembic commands ###
