"""update bookings table

Revision ID: 22d30596da4e
Revises: 39cda4c768ad
Create Date: 2026-08-02 17:14:46.451301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d30596da4e'
down_revision: Union[str, Sequence[str], None] = '39cda4c768ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_number', sa.String(length=30), nullable=True))
    op.add_column('bookings', sa.Column('estimated_distance', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('estimated_fare', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('final_fare', sa.Float(), nullable=True))
    op.add_column("bookings", sa.Column('payment_status',sa.String(50),nullable=False,server_default="pending"))
    op.add_column('bookings', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('bookings', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('is_active',  sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.create_index(op.f('ix_bookings_drop_location_id'), 'bookings', ['drop_location_id'], unique=False)
    op.create_index(op.f('ix_bookings_email'), 'bookings', ['email'], unique=False)
    op.create_index(op.f('ix_bookings_phone'), 'bookings', ['phone'], unique=False)
    op.create_index(op.f('ix_bookings_pickup_location_id'), 'bookings', ['pickup_location_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pickup_location_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_phone'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_email'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_drop_location_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'is_active')
    op.drop_column('bookings', 'vehicle_id')
    op.drop_column('bookings', 'driver_id')
    op.drop_column('bookings', 'payment_method')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'final_fare')
    op.drop_column('bookings', 'estimated_fare')
    op.drop_column('bookings', 'estimated_duration')
    op.drop_column('bookings', 'estimated_distance')
    op.drop_column('bookings', 'booking_number')
    # ### end Alembic commands ###
