"""make pickup_time nullable

Revision ID: 39cda4c768ad
Revises: ec6c2db832bc
Create Date: 2026-08-02 16:34:34.712586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39cda4c768ad'
down_revision: Union[str, Sequence[str], None] = 'ec6c2db832bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'pickup_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('bookings', 'car_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'car_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bookings', 'pickup_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
