"""add hindi fields to popular routes

Revision ID: 6ee708a5e608
Revises: 14b497fb0ef6
Create Date: 2026-08-03 11:05:29.246135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee708a5e608'
down_revision: Union[str, Sequence[str], None] = '14b497fb0ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular_routes', sa.Column('from_city_hi', sa.String(length=100), nullable=True))
    op.add_column('popular_routes', sa.Column('to_city_hi', sa.String(length=100), nullable=True))
    op.add_column('popular_routes', sa.Column('distance_hi', sa.String(length=50), nullable=True))
    op.add_column('popular_routes', sa.Column('trip_time_hi', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('popular_routes', 'trip_time_hi')
    op.drop_column('popular_routes', 'distance_hi')
    op.drop_column('popular_routes', 'to_city_hi')
    op.drop_column('popular_routes', 'from_city_hi')
    # ### end Alembic commands ###
