"""create trip types table

Revision ID: 7ea39e5acac0
Revises: 193103f0b8bd
Create Date: 2026-07-22 10:08:29.263209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea39e5acac0'
down_revision: Union[str, Sequence[str], None] = '193103f0b8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_types_id'), 'trip_types', ['id'], unique=False)
    op.create_index(op.f('ix_trip_types_slug'), 'trip_types', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_types_slug'), table_name='trip_types')
    op.drop_index(op.f('ix_trip_types_id'), table_name='trip_types')
    op.drop_table('trip_types')
    # ### end Alembic commands ###
