"""update_locations_for_i18n_seo

Revision ID: 95ce293ff61d
Revises: bd2b1c7c871d
Create Date: 2026-08-03 23:19:35.190615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ce293ff61d'
down_revision: Union[str, Sequence[str], None] = 'bd2b1c7c871d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('name_hi', sa.String(length=150), nullable=True))
    op.add_column('locations', sa.Column('country_hi', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('state_hi', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('district_hi', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('sub_district_hi', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('block_hi', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('panchayat_hi', sa.String(length=150), nullable=True))
    op.add_column('locations', sa.Column('seo_title', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('seo_title_hi', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('seo_description', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('seo_description_hi', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('keywords', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('keywords_hi', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('content_hi', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('banner_image', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('thumbnail_image', sa.String(length=255), nullable=True))
    op.add_column('locations', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('locations', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_location_active', 'locations', ['is_active'], unique=False)
    op.create_index('idx_location_featured', 'locations', ['is_featured'], unique=False)
    op.create_index('idx_location_name_hi', 'locations', ['name_hi'], unique=False)
    op.create_index('idx_location_slug', 'locations', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_location_slug', table_name='locations')
    op.drop_index('idx_location_name_hi', table_name='locations')
    op.drop_index('idx_location_featured', table_name='locations')
    op.drop_index('idx_location_active', table_name='locations')
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'is_featured')
    op.drop_column('locations', 'is_active')
    op.drop_column('locations', 'thumbnail_image')
    op.drop_column('locations', 'banner_image')
    op.drop_column('locations', 'content_hi')
    op.drop_column('locations', 'content')
    op.drop_column('locations', 'keywords_hi')
    op.drop_column('locations', 'keywords')
    op.drop_column('locations', 'seo_description_hi')
    op.drop_column('locations', 'seo_description')
    op.drop_column('locations', 'seo_title_hi')
    op.drop_column('locations', 'seo_title')
    op.drop_column('locations', 'panchayat_hi')
    op.drop_column('locations', 'block_hi')
    op.drop_column('locations', 'sub_district_hi')
    op.drop_column('locations', 'district_hi')
    op.drop_column('locations', 'state_hi')
    op.drop_column('locations', 'country_hi')
    op.drop_column('locations', 'name_hi')
    # ### end Alembic commands ###
