"""create locations table

Revision ID: ccc0eaea6c96
Revises: 
Create Date: 2026-07-21 15:48:03.356290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc0eaea6c96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('sub_district', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_location_district', 'locations', ['district'], unique=False)
    op.create_index('idx_location_name', 'locations', ['name'], unique=False)
    op.create_index('idx_location_state', 'locations', ['state'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index('idx_location_state', table_name='locations')
    op.drop_index('idx_location_name', table_name='locations')
    op.drop_index('idx_location_district', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
