"""add hindi fields to testimonial routes

Revision ID: dbaa05ba7067
Revises: 6ee708a5e608
Create Date: 2026-08-03 11:44:07.469859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaa05ba7067'
down_revision: Union[str, Sequence[str], None] = '6ee708a5e608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('name_hi', sa.String(length=100), nullable=True))
    op.add_column('testimonials', sa.Column('designation_hi', sa.String(length=150), nullable=True))
    op.add_column('testimonials', sa.Column('content_hi', sa.Text(), nullable=True))
    op.add_column('testimonials', sa.Column("rating", sa.Float(), nullable=False, server_default="4.5"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'rating')
    op.drop_column('testimonials', 'content_hi')
    op.drop_column('testimonials', 'designation_hi')
    op.drop_column('testimonials', 'name_hi')
    # ### end Alembic commands ###
