"""add phone and subject to contacts

Revision ID: e68db430b084
Revises: 6b78b9132301
Create Date: 2026-07-24 15:12:22.540400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68db430b084'
down_revision: Union[str, Sequence[str], None] = '6b78b9132301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('consent', sa.Boolean(), nullable=False))
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('contacts', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('contacts', 'consent')
    # ### end Alembic commands ###
